"""baseline

Revision ID: 0090689752f2
Revises: b230598b7640
Create Date: 2025-11-22 12:32:08.661512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0090689752f2'
down_revision = 'b230598b7640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
